/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyPOS.login;

import control.ApplicationDataManager;
import dbOperations.LoginDBOperation;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import dataModels.Language;
import java.util.Locale;
import java.util.ResourceBundle;
import easyPOS.localization.ApplicationMessages;
import javax.swing.JOptionPane;
import uiUtil.EasyPOSMessageDialog;

/**
 *
 * @author malit
 */
public class ForgotPwdPanel extends javax.swing.JPanel implements control.LanguageChangeListener {

    /**
     * Creates new form ForgotPwdPanel
     */
    public ForgotPwdPanel() {
        initComponents();
        switchLanguage();
        control.EventManager.getInstance().addLanguageChangeListener(this);
    }

    @Override
    public void onLanguageChanged() {
        switchLanguage();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldUsrName = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jComboBoxFPwd1 = new javax.swing.JComboBox();
        jTextFieldFPwdAns1 = new javax.swing.JTextField();
        jButtonFogotLogin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jPanel24.setBackground(new java.awt.Color(0, 204, 255));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setText("User Name:");

        jTextFieldUsrName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setText("Answer:");

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setText("Hint:");

        jComboBoxFPwd1.setBackground(new java.awt.Color(0, 204, 255));
        jComboBoxFPwd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxFPwd1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your Favourite Movie?", "Your mother's maiden name", "Your favourite place?", "Your place of birth?" }));

        jTextFieldFPwdAns1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonFogotLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonFogotLogin.setText("OK");
        jButtonFogotLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFogotLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFogotLogin)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsrName)
                            .addComponent(jTextFieldFPwdAns1)
                            .addComponent(jComboBoxFPwd1, 0, 250, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jTextFieldUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(jComboBoxFPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jTextFieldFPwdAns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFogotLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchLanguage() {
        Language appLang = ApplicationDataManager.getInstance().getApplicationLanguage();
        Locale locale = (appLang == Language.SINHALA) ? new Locale("si", "LK") : Locale.ENGLISH;
        ResourceBundle resourceBundle = ResourceBundle.getBundle("easyPOS/login/Bundle", locale);
        if (appLang == Language.SINHALA) {
        try {
            Font customFont = Font.createFont(Font.TRUETYPE_FONT,
                    ApplicationDataManager.getInstance().getSinhalaFontFile()).deriveFont(12f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(customFont);
            jLabel54.setFont(customFont);
            jLabel55.setFont(customFont);
            jLabel56.setFont(customFont);
            jButtonFogotLogin.setFont(customFont);
        } catch (IOException | FontFormatException e) {
            System.err.println(e);
        }
        }
        jLabel54.setText(resourceBundle.getString("ForgotPwdPanel.jLabel54.text"));
        jLabel55.setText(resourceBundle.getString("ForgotPwdPanel.jLabel55.text"));
        jLabel56.setText(resourceBundle.getString("ForgotPwdPanel.jLabel56.text"));
        jButtonFogotLogin.setText(resourceBundle.getString("ForgotPwdPanel.jButtonFogotLogin.text"));
    }

    private void jButtonFogotLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFogotLoginActionPerformed
        int indx=jComboBoxFPwd1.getSelectedIndex();
        String index="";
        switch(indx){
            case 0:
            index="1";break;
            case 1:
            index="2";break;
            case 2:
            index="3";break;
            case 3:
            index="4";break;
        }
        LoginDBOperation ls=new LoginDBOperation();
        int dbResult=ls.checkPassWordHint(jTextFieldUsrName.getText(), jTextFieldFPwdAns1.getText(), index);

        if(dbResult==0){//you can log and change pwd

//            currentUser=jTextFieldUsrName.getText();
            jTextFieldUsrName.setText("");
            jTextFieldFPwdAns1.setText("");
//            currentUserData();
//            String res=ls.toGetPwd(currentUser);
//            if(res.equals("mali")){
//                JOptionPane.showMessageDialog(this, "If you can't remember your password...\n you can't change your password!");
//            }else{
//                jPasswordFieldCurPwd.setText(res);
//            }
            //load old pwd to change pwd
        }else if(dbResult==1){
            EasyPOSMessageDialog.showLocalizedWarning(this, ApplicationMessages.VALIDATION_SUBMISSION_MISMATCH);
        }else if(dbResult==2){
            EasyPOSMessageDialog.showLocalizedError(this, ApplicationMessages.ERROR_DATA_CONNECTION);
        }

    }//GEN-LAST:event_jButtonFogotLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFogotLogin;
    private javax.swing.JComboBox jComboBoxFPwd1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JTextField jTextFieldFPwdAns1;
    private javax.swing.JTextField jTextFieldUsrName;
    // End of variables declaration//GEN-END:variables
}
