package easyPOS.settings;

import control.ApplicationDataManager;
import dataModels.UserDataModel;
import dbOperations.LoginDBOperation;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author malit
 */
public class SettingsPanel extends javax.swing.JPanel {

    
    LoginDBOperation logScr=new LoginDBOperation();
    
    int accountType=0;
    String currentUser="";
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        switchLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldUserFrstNme = new javax.swing.JTextField();
        jTextFieldUserLsttNme = new javax.swing.JTextField();
        jCheckBoxCreateAdminAcc = new javax.swing.JCheckBox();
        jPasswordFieldCreatePwd = new javax.swing.JPasswordField();
        jPasswordFieldCreatePwd2 = new javax.swing.JPasswordField();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jPanelSettingsPwdChangeDelete = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jButtonChangeAcc = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jPasswordFieldChangePwd = new javax.swing.JPasswordField();
        jPasswordFieldChangePwd2 = new javax.swing.JPasswordField();
        jLabel66 = new javax.swing.JLabel();
        jPasswordFieldCurPwd = new javax.swing.JPasswordField();
        jButton41 = new javax.swing.JButton();
        jButtonDelUserAcc = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jTextFieldUserNme = new javax.swing.JTextField();
        jPanelAccessLevels1 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jCheckBoxStock = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel30 = new javax.swing.JPanel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jLabel67 = new javax.swing.JLabel();
        jTextFieldSecAns = new javax.swing.JTextField();
        jComboBoxCreateAcc = new javax.swing.JComboBox();
        jLabel85 = new javax.swing.JLabel();
        jPanelAccessLevels = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jPanel27 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextAreaUserAccounts = new javax.swing.JTextArea();
        jTextFieldDelAcc = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jTextFieldNoOfFieldsinvoices = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel80 = new javax.swing.JLabel();
        jPasswordForClear = new javax.swing.JPasswordField();
        jLabel89 = new javax.swing.JLabel();
        jCheckBoxClear1 = new javax.swing.JCheckBox();
        jLabel90 = new javax.swing.JLabel();
        jPasswordForClear2 = new javax.swing.JPasswordField();
        jLabel91 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jCheckBoxClear2 = new javax.swing.JCheckBox();
        jCheckBoxClear3 = new javax.swing.JCheckBox();
        jCheckBoxClear4 = new javax.swing.JCheckBox();

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel18.setPreferredSize(new java.awt.Dimension(1034, 550));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("First Name:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Last Name:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Password:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Type password Again:");

        jTextFieldUserFrstNme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldUserLsttNme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jCheckBoxCreateAdminAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxCreateAdminAcc.setText("Create an Administrator Account");

        jPasswordFieldCreatePwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordFieldCreatePwd2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton28.setText("Create");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton29.setText("Cancel");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton30.setText("Change Password");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton31.setText("Delete Account");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel62.setText("New Password:");

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel63.setText("User Name:");

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel61.setText("Type password Again:");

        jButtonChangeAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonChangeAcc.setText("OK");
        jButtonChangeAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeAccActionPerformed(evt);
            }
        });

        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordFieldChangePwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordFieldChangePwd2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("Current Password:");

        jPasswordFieldCurPwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton41.setText("Cancel");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButtonDelUserAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDelUserAcc.setText("Delete");
        jButtonDelUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelUserAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingsPwdChangeDeleteLayout = new javax.swing.GroupLayout(jPanelSettingsPwdChangeDelete);
        jPanelSettingsPwdChangeDelete.setLayout(jPanelSettingsPwdChangeDeleteLayout);
        jPanelSettingsPwdChangeDeleteLayout.setHorizontalGroup(
            jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsPwdChangeDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsPwdChangeDeleteLayout.createSequentialGroup()
                        .addComponent(jButton41)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSettingsPwdChangeDeleteLayout.createSequentialGroup()
                        .addComponent(jButtonDelUserAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChangeAcc))
                    .addComponent(jTextField25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldCurPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldChangePwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldChangePwd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelSettingsPwdChangeDeleteLayout.setVerticalGroup(
            jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsPwdChangeDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldCurPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jPasswordFieldChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jPasswordFieldChangePwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsPwdChangeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChangeAcc)
                    .addComponent(jButton41)
                    .addComponent(jButtonDelUserAcc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("User Name:");

        jTextFieldUserNme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stocks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBoxStock.setText("Stocks");

        jCheckBox3.setText("Enable editing Stoke");

        jCheckBox13.setText("Enable deleting Stoke");

        jCheckBox14.setText("Enable adding new item to Stoke");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBoxStock))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxStock)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(3, 3, 3)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox14))
        );

        jButton39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton39.setText("Save Settings");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton40.setText("Cancel");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jLabel65.setText("Access Lavels For Normal Users.....");

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBox15.setText("Supplies");

        jCheckBox16.setText("Enable adding new suppliers");

        jCheckBox17.setText("Enable editing suppliers data");

        jCheckBox18.setText("Enable deleting suppliers data");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addComponent(jCheckBox15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCheckBox17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox15)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBox19.setText("Reports");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jCheckBox19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAccessLevels1Layout = new javax.swing.GroupLayout(jPanelAccessLevels1);
        jPanelAccessLevels1.setLayout(jPanelAccessLevels1Layout);
        jPanelAccessLevels1Layout.setHorizontalGroup(
            jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccessLevels1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAccessLevels1Layout.createSequentialGroup()
                        .addGroup(jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton40)
                            .addGroup(jPanelAccessLevels1Layout.createSequentialGroup()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccessLevels1Layout.setVerticalGroup(
            jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccessLevels1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAccessLevels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton39)
                    .addComponent(jButton40))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("Security Answer:");

        jTextFieldSecAns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxCreateAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCreateAcc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your Favourite Movie?", "Your mother's maiden name", "Your favourite place?", "Your place of birth?" }));

        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAccessLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel85)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanelSettingsPwdChangeDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSecAns, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPasswordFieldCreatePwd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUserNme, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUserLsttNme, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUserFrstNme, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBoxCreateAdminAcc)
                                        .addGroup(jPanel18Layout.createSequentialGroup()
                                            .addComponent(jButton29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton28)))
                                    .addComponent(jPasswordFieldCreatePwd2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jTextFieldUserFrstNme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton30))
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton31))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldUserLsttNme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel64)
                                    .addComponent(jTextFieldUserNme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(jTextFieldSecAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jPasswordFieldCreatePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jPasswordFieldCreatePwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCreateAdminAcc)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanelSettingsPwdChangeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton29)
                            .addComponent(jButton28))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAccessLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("User Accounts", jPanel18);

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stocks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBox5.setText("Stocks");

        jCheckBox2.setText("Enable editing Stoke");

        jCheckBox8.setText("Enable deleting Stoke");

        jCheckBox9.setText("Enable adding new item to Stoke");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox5)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(3, 3, 3)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox9)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel39.setText("Access Lavels For Normal Users.....");

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBox4.setText("Supplies");

        jCheckBox10.setText("Enable adding new suppliers");

        jCheckBox11.setText("Enable editing suppliers data");

        jCheckBox12.setText("Enable deleting suppliers data");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCheckBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBox6.setText("Reports");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox6)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jCheckBox6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Delete Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextAreaUserAccounts.setEditable(false);
        jTextAreaUserAccounts.setBackground(new java.awt.Color(224, 223, 233));
        jTextAreaUserAccounts.setColumns(20);
        jTextAreaUserAccounts.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextAreaUserAccounts.setRows(5);
        jScrollPane13.setViewportView(jTextAreaUserAccounts);

        jTextFieldDelAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("User Name:");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAccessLevelsLayout = new javax.swing.GroupLayout(jPanelAccessLevels);
        jPanelAccessLevels.setLayout(jPanelAccessLevelsLayout);
        jPanelAccessLevelsLayout.setHorizontalGroup(
            jPanelAccessLevelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccessLevelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccessLevelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccessLevelsLayout.createSequentialGroup()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccessLevelsLayout.setVerticalGroup(
            jPanelAccessLevelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccessLevelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccessLevelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAccessLevelsLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAccessLevelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Access Levels", jPanelAccessLevels);

        jLabel40.setText("Port Number:");

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reset Memory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        jTextFieldNoOfFieldsinvoices.setEditable(false);
        jTextFieldNoOfFieldsinvoices.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNoOfFieldsinvoices.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setText("OK");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel80.setText("Password:");

        jPasswordForClear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel89.setText("Invoice Data of Sale invoices");

        jCheckBoxClear1.setText("Clear");

        jLabel90.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel90.setText("Password2:");

        jPasswordForClear2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel91.setText("Sold item data ( invoice wise)");

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel92.setText("Sales data daily");

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel93.setText("Sales data Monthly");

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCheckBoxClear2.setText("Clear");

        jCheckBoxClear3.setText("Clear");

        jCheckBoxClear4.setText("Clear");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jPasswordForClear2))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordForClear))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNoOfFieldsinvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxClear1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jCheckBoxClear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxClear3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxClear4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNoOfFieldsinvoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89)
                    .addComponent(jCheckBoxClear1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxClear2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxClear3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel93)
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxClear4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(jPasswordForClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(jPasswordForClear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton17))
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Advanced Settings", jPanel21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        jPanelSettingsPwdChangeDelete.setVisible(false);

        if(jTextFieldUserNme.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill the required fields !");
        }else{
            if(jCheckBoxCreateAdminAcc.isSelected()){//create administrator account
                if(accountType==1){//if loged in admin account?
                    if(jPasswordFieldCreatePwd.getText().equals(jPasswordFieldCreatePwd2.getText())){
                        //create admin account
                        UserDataModel usrv=new UserDataModel();

                        usrv.setAccountType(1);
                        usrv.setUserName(jTextFieldUserNme.getText());
                        usrv.setPassword(jPasswordFieldCreatePwd.getText());
                        usrv.setPwdHint(jTextFieldSecAns.getText());
                        usrv.setHintType(jComboBoxCreateAcc.getSelectedIndex() + 1);
                        usrv.setStocks(1);
                        usrv.setEditStocks(1);
                        usrv.setAddStocks(1);
                        usrv.setDelStocks(1);
                        usrv.setSupplies(1);
                        usrv.setAddSupplies(1);
                        usrv.setEditSupplies(1);
                        usrv.setDelSupplies(1);
                        usrv.setReports(1);

                        boolean res=logScr.addNewUser(usrv);
                        if(res==true){
                            JOptionPane.showMessageDialog(this, "Your account is successfully created !");
                            //clear fields
                            clearFieldsAddNewUser();
                        }else{
                            JOptionPane.showMessageDialog(this, "Can not do your process !");
                        }

                    }else{//pwd mismatch
                        JOptionPane.showMessageDialog(this, "passwords do not match !");
                        jPasswordFieldCreatePwd.setText("");
                        jPasswordFieldCreatePwd.setText("");
                    }
                    //create account.....
                }else{
                    JOptionPane.showMessageDialog(this, "You should loggin with administrater account !");
                }

            }else{//normal account
                //show access levels
                jPanelAccessLevels1.setVisible(true);

            }
        }

    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        jPanelAccessLevels1.setVisible(false);
        clearFieldsAddNewUser();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        jPanelSettingsPwdChangeDelete.setVisible(true);
        jButtonChangeAcc.setVisible(true);
        jButtonDelUserAcc.setVisible(false);
        jPasswordFieldChangePwd.setVisible(true);
        jPasswordFieldChangePwd2.setVisible(true);
        jLabel62.setVisible(true);
        jLabel61.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        jPanelSettingsPwdChangeDelete.setVisible(true);
        jButtonDelUserAcc.setVisible(true);
        jButtonChangeAcc.setVisible(false);
        jPasswordFieldChangePwd.setVisible(false);
        jPasswordFieldChangePwd2.setVisible(false);
        jLabel62.setVisible(false);
        jLabel61.setVisible(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButtonChangeAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeAccActionPerformed
        if(jPasswordFieldChangePwd.getText().equals(jPasswordFieldChangePwd2.getText())){
            int res=logScr.checkPassWord(currentUser, jPasswordFieldCurPwd.getText());
            if(res==0){
                //change account password
                boolean res2=logScr.changeUserPwd(currentUser, jPasswordFieldChangePwd.getText());
                if(res2==true){
                    JOptionPane.showMessageDialog(this, "Password has been changed !");
                    //clear fields
                    jTextField25.setText("");
                    jPasswordFieldCurPwd.setText("");
                    jPasswordFieldChangePwd.setText("");
                    jPasswordFieldChangePwd2.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Can not do your process now !");
                }

            }else{
                JOptionPane.showMessageDialog(this, "Current password does not match !");
            }
        }else{
            JOptionPane.showMessageDialog(this, "New passwords do not match !");
        }

    }//GEN-LAST:event_jButtonChangeAccActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        jPanelSettingsPwdChangeDelete.setVisible(false);
        jTextField25.setText("");
        jPasswordFieldChangePwd.setText("");
        jPasswordFieldChangePwd2.setText("");
        jPasswordFieldCurPwd.setText("");
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButtonDelUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelUserAccActionPerformed
        if(jPasswordFieldChangePwd.getText().equals(jPasswordFieldChangePwd2.getText())){
            int res=logScr.checkPassWord(currentUser, jPasswordFieldCurPwd.getText());
            if(res==0){
                //delete account
                boolean res2=logScr.deleteUserAccount(currentUser);
                if(res2==true){
                    JOptionPane.showMessageDialog(this, "Your account is deleted !");
                    //clear fields
                    jTextField25.setText("");
                    jPasswordFieldCurPwd.setText("");
                    jPasswordFieldChangePwd.setText("");
                    jPasswordFieldChangePwd2.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Can not do your process now !");
                }

            }else{
                JOptionPane.showMessageDialog(this, "Current password does not match !");
            }
        }else{
            JOptionPane.showMessageDialog(this, "New passwords do not match !");
        }
    }//GEN-LAST:event_jButtonDelUserAccActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        //create normal account
        String controlSet="";

        if(jTextFieldUserNme.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill the required fields !");
        }else{
            if(logScr.userType(currentUser)==true){//if loged in admin account?
                if(jPasswordFieldCreatePwd.getText().equals(jPasswordFieldCreatePwd2.getText())){

                    UserDataModel usrv=new UserDataModel();

                    usrv.setAccountType(0);
                    usrv.setUserName(jTextFieldUserNme.getText());
                    usrv.setPassword(jPasswordFieldCreatePwd.getText());
                    usrv.setPwdHint(jTextFieldSecAns.getText());
                    usrv.setHintType(jComboBoxCreateAcc.getSelectedIndex() + 1);
                    if(jCheckBoxStock.isSelected()){
                        usrv.setStocks(1);
                    }else{
                        usrv.setStocks(0);
                    }
                    if(jCheckBox3.isSelected()){
                        usrv.setEditStocks(1);
                    }else{
                        usrv.setEditStocks(0);
                    }
                    if(jCheckBox14.isSelected()){
                        usrv.setAddStocks(1);
                    }else{
                        usrv.setAddStocks(0);
                    }
                    if(jCheckBox13.isSelected()){
                        usrv.setDelStocks(1);
                    }else{
                        usrv.setDelStocks(0);
                    }

                    if(jCheckBox15.isSelected()){
                        usrv.setSupplies(1);
                    }else{
                        usrv.setSupplies(0);
                    }
                    if(jCheckBox16.isSelected()){
                        usrv.setAddSupplies(1);
                    }else{
                        usrv.setAddSupplies(0);
                    }
                    if(jCheckBox17.isSelected()){
                        usrv.setEditSupplies(1);
                    }else{
                        usrv.setEditSupplies(0);
                    }
                    if(jCheckBox18.isSelected()){
                        usrv.setDelSupplies(1);
                    }else{
                        usrv.setDelSupplies(0);
                    }
                    if(jCheckBox19.isSelected()){
                        usrv.setReports(1);
                    }else{
                        usrv.setReports(0);
                    }

                    boolean res=logScr.addNewUser(usrv);
                    if(res==true){
                        JOptionPane.showMessageDialog(this, "Your account is successfully created !");
                        //clear fields
                        clearFieldsAddNewUser();
                        //hide panel
                        jPanelAccessLevels1.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Can not do your process !");
                    }

                }else{//pwd mismatch
                    JOptionPane.showMessageDialog(this, "passwords do not match !");
                    jPasswordFieldCreatePwd.setText("");
                    jPasswordFieldCreatePwd.setText("");
                }

            }else{
                JOptionPane.showMessageDialog(this, "You should loggin with administrater account !");
            }

        }

        /*
        if(DB result==ok){
            JOptionPane.showMessageDialog(this, "Normal use account is successfully created.");
            jPanelAccessLevels1.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Can not do your process.");
        }*/

    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        jPanelAccessLevels1.setVisible(false);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //delete account
        if(logScr.userType(currentUser)==true){
            if(logScr.userType(jTextFieldDelAcc.getText())==true){
                JOptionPane.showMessageDialog(this, "You can't delete administrator Accounts!");
            }else{
                boolean res=logScr.deleteUserAccount(jTextFieldDelAcc.getText());
                if(res==true){
                    JOptionPane.showMessageDialog(this, "Account is deleted !");
                    //clear fields
                    jTextFieldDelAcc.setText("");
                    //load text area
                    if(logScr.userType(currentUser)==true){
                        jTextAreaUserAccounts.setText(logScr.usersList());
                    }

                }else{
                    JOptionPane.showMessageDialog(this, "Can not do your process now !");
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextFieldDelAcc.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        ////        //clear DB tables
        ////        if(accountType==1){
            ////            int ans=JOptionPane.showConfirmDialog(this, "Are you sure?\nDo you want to permanently delete this data?");
            ////            if(JOptionPane.YES_OPTION==ans){
                ////                if(logScr.checkPassWord(currentUser,jPasswordForClear.getText())==0&&jPasswordForClear2.getText().equals("1234567890")){
                    ////                    if(jCheckBoxClear1.isSelected()){
                        ////                        //print data
                        ////                        //delete data
                        ////                        boolean res=sdbops.deleteSaleItems(0, 1);
                        ////                        if(res==true){
                            ////                            JOptionPane.showMessageDialog(this, "Successfully cleared your Invoice data1 storages !");
                            ////
                            ////                        }
                        ////                    }
                    ////                    if(jCheckBoxClear2.isSelected()){
                        ////                        //print data
                        ////                        //delete data
                        ////                        boolean res=sdbops.deleteSaleInvoice(dateFormatForDB(jTextFieldDate.getText()));//delete data
                        ////                        if(res==true){
                            ////                            JOptionPane.showMessageDialog(this, "Successfully cleared your Invoice data2 storages !");
                            ////                        }
                        ////                    }
                    ////                    if(jCheckBoxClear3.isSelected()){
                        ////                        //print data
                        ////                        //delete data
                        ////                        boolean res=sdbops.deleteSaleDaily(dateFormatForDB(jTextFieldDate.getText()));//delete data
                        ////                        if(res==true){
                            ////                            JOptionPane.showMessageDialog(this, "Successfully cleared your daily sales data storages !");
                            ////                        }
                        ////                    }
                    ////                    if(jCheckBoxClear4.isSelected()){
                        ////                        //print data
                        ////                        //delete data
                        ////                        boolean res=sdbops.deleteSalesMonthly(dateFormatForDB(jTextFieldDate.getText()));//delete data
                        ////                        if(res==true){
                            ////                            JOptionPane.showMessageDialog(this, "Successfully cleared your monthly sales data storages !");
                            ////                        }
                        ////                    }
                    ////                    jPasswordForClear.setText("");
                    ////                    jPasswordForClear2.setText("");
                    ////                    jCheckBoxClear1.setSelected(false);
                    ////                    jCheckBoxClear2.setSelected(false);
                    ////                    jCheckBoxClear3.setSelected(false);
                    ////                    jCheckBoxClear4.setSelected(false);
                    ////
                    ////                }else{
                    ////                    JOptionPane.showMessageDialog(this, "Password missmatch !");
                    ////                }
                ////
                ////            }
            ////        }else{
            ////            JOptionPane.showMessageDialog(this, "You have not sufficient permission to do this task !");
            ////            jPasswordForClear.setText("");
            ////            jPasswordForClear2.setText("");
            ////        }
        ////
        ////
        ////
    }//GEN-LAST:event_jButton17ActionPerformed

    void clearFieldsAddNewUser(){
        jTextFieldUserFrstNme.setText("");
        jTextFieldUserLsttNme.setText("");
        jTextFieldUserNme.setText("");
        jTextFieldSecAns.setText("");
        jPasswordFieldCreatePwd.setText("");
        jPasswordFieldCreatePwd2.setText("");
    }

    private void switchLanguage() {
        Locale locale = new Locale("si", "LK");
        ResourceBundle resourceBundle = ResourceBundle.getBundle("easyPOS/settings/Bundle", locale);
        try {
            Font customFont = Font.createFont(Font.TRUETYPE_FONT,
                    ApplicationDataManager.getInstance().getSinhalaFontFile()).deriveFont(12f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(customFont);
            jLabel35.setFont(customFont); jLabel36.setFont(customFont);
            jLabel37.setFont(customFont); jLabel38.setFont(customFont);
            jCheckBoxCreateAdminAcc.setFont(customFont);
            jButton28.setFont(customFont); jButton29.setFont(customFont);
            jButton30.setFont(customFont); jButton31.setFont(customFont);
            jLabel62.setFont(customFont); jLabel63.setFont(customFont);
            jLabel61.setFont(customFont); jButtonChangeAcc.setFont(customFont);
            jLabel66.setFont(customFont); jButton41.setFont(customFont);
            jButtonDelUserAcc.setFont(customFont);
            jLabel64.setFont(customFont); jCheckBoxStock.setFont(customFont);
            jCheckBox3.setFont(customFont); jCheckBox13.setFont(customFont);
            jCheckBox14.setFont(customFont);
            jButton39.setFont(customFont); jButton40.setFont(customFont);
            jLabel65.setFont(customFont); jCheckBox15.setFont(customFont);
            jCheckBox16.setFont(customFont); jCheckBox17.setFont(customFont);
            jCheckBox18.setFont(customFont); jCheckBox19.setFont(customFont);
            jLabel67.setFont(customFont);
            jCheckBox5.setFont(customFont); jCheckBox2.setFont(customFont);
            jCheckBox8.setFont(customFont); jCheckBox9.setFont(customFont);
            jLabel39.setFont(customFont); jCheckBox4.setFont(customFont);
            jCheckBox10.setFont(customFont); jCheckBox11.setFont(customFont);
            jCheckBox12.setFont(customFont); jCheckBox6.setFont(customFont);
            jButton1.setFont(customFont); jButton8.setFont(customFont);
            jLabel41.setFont(customFont); jLabel40.setFont(customFont);
            jButton17.setFont(customFont); jLabel80.setFont(customFont);
            jLabel89.setFont(customFont); jCheckBoxClear1.setFont(customFont);
            jLabel90.setFont(customFont); jLabel91.setFont(customFont);
            jLabel92.setFont(customFont); jLabel93.setFont(customFont);
            jCheckBoxClear2.setFont(customFont); jCheckBoxClear3.setFont(customFont);
            jCheckBoxClear4.setFont(customFont);
        } catch (IOException | FontFormatException e) {
            System.err.println(e);
        }
        jTabbedPane3.setTitleAt(0, resourceBundle.getString("SettingsPanel.tab.userAccounts"));
        jTabbedPane3.setTitleAt(1, resourceBundle.getString("SettingsPanel.tab.accessLevels"));
        jTabbedPane3.setTitleAt(2, resourceBundle.getString("SettingsPanel.tab.advancedSettings"));
        jLabel35.setText(resourceBundle.getString("SettingsPanel.jLabel35.text"));
        jLabel36.setText(resourceBundle.getString("SettingsPanel.jLabel36.text"));
        jLabel37.setText(resourceBundle.getString("SettingsPanel.jLabel37.text"));
        jLabel38.setText(resourceBundle.getString("SettingsPanel.jLabel38.text"));
        jCheckBoxCreateAdminAcc.setText(resourceBundle.getString("SettingsPanel.jCheckBoxCreateAdminAcc.text"));
        jButton28.setText(resourceBundle.getString("SettingsPanel.jButton28.text"));
        jButton29.setText(resourceBundle.getString("SettingsPanel.jButton29.text"));
        jButton30.setText(resourceBundle.getString("SettingsPanel.jButton30.text"));
        jButton31.setText(resourceBundle.getString("SettingsPanel.jButton31.text"));
        jLabel62.setText(resourceBundle.getString("SettingsPanel.jLabel62.text"));
        jLabel63.setText(resourceBundle.getString("SettingsPanel.jLabel63.text"));
        jLabel61.setText(resourceBundle.getString("SettingsPanel.jLabel61.text"));
        jButtonChangeAcc.setText(resourceBundle.getString("SettingsPanel.jButtonChangeAcc.text"));
        jLabel66.setText(resourceBundle.getString("SettingsPanel.jLabel66.text"));
        jButton41.setText(resourceBundle.getString("SettingsPanel.jButton41.text"));
        jButtonDelUserAcc.setText(resourceBundle.getString("SettingsPanel.jButtonDelUserAcc.text"));
        jLabel64.setText(resourceBundle.getString("SettingsPanel.jLabel64.text"));
        jCheckBoxStock.setText(resourceBundle.getString("SettingsPanel.jCheckBoxStock.text"));
        jCheckBox3.setText(resourceBundle.getString("SettingsPanel.jCheckBox3.text"));
        jCheckBox13.setText(resourceBundle.getString("SettingsPanel.jCheckBox13.text"));
        jCheckBox14.setText(resourceBundle.getString("SettingsPanel.jCheckBox14.text"));
        jButton39.setText(resourceBundle.getString("SettingsPanel.jButton39.text"));
        jButton40.setText(resourceBundle.getString("SettingsPanel.jButton40.text"));
        jLabel65.setText(resourceBundle.getString("SettingsPanel.jLabel65.text"));
        jCheckBox15.setText(resourceBundle.getString("SettingsPanel.jCheckBox15.text"));
        jCheckBox16.setText(resourceBundle.getString("SettingsPanel.jCheckBox16.text"));
        jCheckBox17.setText(resourceBundle.getString("SettingsPanel.jCheckBox17.text"));
        jCheckBox18.setText(resourceBundle.getString("SettingsPanel.jCheckBox18.text"));
        jCheckBox19.setText(resourceBundle.getString("SettingsPanel.jCheckBox19.text"));
        jLabel67.setText(resourceBundle.getString("SettingsPanel.jLabel67.text"));
        jCheckBox5.setText(resourceBundle.getString("SettingsPanel.jCheckBox5.text"));
        jCheckBox2.setText(resourceBundle.getString("SettingsPanel.jCheckBox2.text"));
        jCheckBox8.setText(resourceBundle.getString("SettingsPanel.jCheckBox8.text"));
        jCheckBox9.setText(resourceBundle.getString("SettingsPanel.jCheckBox9.text"));
        jLabel39.setText(resourceBundle.getString("SettingsPanel.jLabel39.text"));
        jCheckBox4.setText(resourceBundle.getString("SettingsPanel.jCheckBox4.text"));
        jCheckBox10.setText(resourceBundle.getString("SettingsPanel.jCheckBox10.text"));
        jCheckBox11.setText(resourceBundle.getString("SettingsPanel.jCheckBox11.text"));
        jCheckBox12.setText(resourceBundle.getString("SettingsPanel.jCheckBox12.text"));
        jCheckBox6.setText(resourceBundle.getString("SettingsPanel.jCheckBox6.text"));
        jButton1.setText(resourceBundle.getString("SettingsPanel.jButton1.text"));
        jButton8.setText(resourceBundle.getString("SettingsPanel.jButton8.text"));
        jLabel41.setText(resourceBundle.getString("SettingsPanel.jLabel41.text"));
        jLabel40.setText(resourceBundle.getString("SettingsPanel.jLabel40.text"));
        jButton17.setText(resourceBundle.getString("SettingsPanel.jButton17.text"));
        jLabel80.setText(resourceBundle.getString("SettingsPanel.jLabel80.text"));
        jLabel89.setText(resourceBundle.getString("SettingsPanel.jLabel89.text"));
        jCheckBoxClear1.setText(resourceBundle.getString("SettingsPanel.jCheckBoxClear1.text"));
        jLabel90.setText(resourceBundle.getString("SettingsPanel.jLabel90.text"));
        jLabel91.setText(resourceBundle.getString("SettingsPanel.jLabel91.text"));
        jLabel92.setText(resourceBundle.getString("SettingsPanel.jLabel92.text"));
        jLabel93.setText(resourceBundle.getString("SettingsPanel.jLabel93.text"));
        jCheckBoxClear2.setText(resourceBundle.getString("SettingsPanel.jCheckBoxClear2.text"));
        jCheckBoxClear3.setText(resourceBundle.getString("SettingsPanel.jCheckBoxClear3.text"));
        jCheckBoxClear4.setText(resourceBundle.getString("SettingsPanel.jCheckBoxClear4.text"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonChangeAcc;
    private javax.swing.JButton jButtonDelUserAcc;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBoxClear1;
    private javax.swing.JCheckBox jCheckBoxClear2;
    private javax.swing.JCheckBox jCheckBoxClear3;
    private javax.swing.JCheckBox jCheckBoxClear4;
    private javax.swing.JCheckBox jCheckBoxCreateAdminAcc;
    private javax.swing.JCheckBox jCheckBoxStock;
    private javax.swing.JComboBox jComboBoxCreateAcc;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanelAccessLevels;
    private javax.swing.JPanel jPanelAccessLevels1;
    private javax.swing.JPanel jPanelSettingsPwdChangeDelete;
    private javax.swing.JPasswordField jPasswordFieldChangePwd;
    private javax.swing.JPasswordField jPasswordFieldChangePwd2;
    private javax.swing.JPasswordField jPasswordFieldCreatePwd;
    private javax.swing.JPasswordField jPasswordFieldCreatePwd2;
    private javax.swing.JPasswordField jPasswordFieldCurPwd;
    private javax.swing.JPasswordField jPasswordForClear;
    private javax.swing.JPasswordField jPasswordForClear2;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextAreaUserAccounts;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldDelAcc;
    private javax.swing.JTextField jTextFieldNoOfFieldsinvoices;
    private javax.swing.JTextField jTextFieldSecAns;
    private javax.swing.JTextField jTextFieldUserFrstNme;
    private javax.swing.JTextField jTextFieldUserLsttNme;
    private javax.swing.JTextField jTextFieldUserNme;
    // End of variables declaration//GEN-END:variables
}
