/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author MalithWanniarachchi
 */
public class CustomerScreenLogoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerScreenLogoPanel
     */
    public CustomerScreenLogoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cusScreenLogoGreetingLbl = new javax.swing.JLabel();
        cusScreenLogoGreetingLbl2 = new javax.swing.JLabel();
        cusScreenLogoGreetingLbl3 = new javax.swing.JLabel();
        cusScreenLogoAddressLbl = new javax.swing.JLabel();
        cusScreenLogoLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        cusScreenLogoGreetingLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cusScreenLogoGreetingLbl.setForeground(new java.awt.Color(255, 204, 51));
        cusScreenLogoGreetingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cusScreenLogoGreetingLbl.setText("Hello !");

        cusScreenLogoGreetingLbl2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cusScreenLogoGreetingLbl2.setForeground(new java.awt.Color(255, 204, 51));
        cusScreenLogoGreetingLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cusScreenLogoGreetingLbl2.setText("It is a brand new day.");

        cusScreenLogoGreetingLbl3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cusScreenLogoGreetingLbl3.setForeground(new java.awt.Color(255, 204, 51));
        cusScreenLogoGreetingLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cusScreenLogoGreetingLbl3.setText("Welcome to");

        cusScreenLogoAddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cusScreenLogoAddressLbl.setForeground(new java.awt.Color(255, 204, 51));
        cusScreenLogoAddressLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cusScreenLogoAddressLbl.setText("Branch Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cusScreenLogoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cusScreenLogoGreetingLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cusScreenLogoGreetingLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(cusScreenLogoGreetingLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(cusScreenLogoAddressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cusScreenLogoGreetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusScreenLogoGreetingLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusScreenLogoGreetingLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cusScreenLogoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cusScreenLogoAddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cusScreenLogoAddressLbl;
    private javax.swing.JLabel cusScreenLogoGreetingLbl;
    private javax.swing.JLabel cusScreenLogoGreetingLbl2;
    private javax.swing.JLabel cusScreenLogoGreetingLbl3;
    private javax.swing.JLabel cusScreenLogoLbl;
    // End of variables declaration//GEN-END:variables
}
