
package javaapplication1;

/**
 *
 * @author MalithWanniarachchi
 */
public class CustomerScreenInvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerScreenLogoPanel
     */
    public CustomerScreenInvoicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        custDisplayItemsLabel = new javax.swing.JLabel();
        custDisplayTotalLabel = new javax.swing.JLabel();
        custDisplayDiscountLabel = new javax.swing.JLabel();
        custDisplayNetAmtLabel = new javax.swing.JLabel();
        custDisplayDueAmtLabel = new javax.swing.JLabel();
        custDisplayChangeAmtLabel = new javax.swing.JLabel();
        custDisplayItemsValueLabel = new javax.swing.JLabel();
        custDisplayTotalValueLabel = new javax.swing.JLabel();
        custDisplayDiscountValueLabel = new javax.swing.JLabel();
        custDisplayNetAmtValueLabel = new javax.swing.JLabel();
        custDisplayDueAmtValueLabel = new javax.swing.JLabel();
        custDisplayChangeAmtValueLabel = new javax.swing.JLabel();
        custDisplayItemsValueLabel1 = new javax.swing.JLabel();
        custDisplayTotalValueLabel1 = new javax.swing.JLabel();
        custDisplayDiscountValueLabel1 = new javax.swing.JLabel();
        custDisplayNetAmtValueLabel1 = new javax.swing.JLabel();
        custDisplayDueAmtValueLabel1 = new javax.swing.JLabel();
        custDisplayChangeAmtValueLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        custDisplayItemsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        custDisplayItemsLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayItemsLabel.setText("Item(s)");

        custDisplayTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        custDisplayTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayTotalLabel.setText("TOTAL");

        custDisplayDiscountLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDiscountLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDiscountLabel.setText("DISCOUNT TOTAL");

        custDisplayNetAmtLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custDisplayNetAmtLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayNetAmtLabel.setText("NET AMOUNT");

        custDisplayDueAmtLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDueAmtLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDueAmtLabel.setText("DUE AMOUNT");

        custDisplayChangeAmtLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayChangeAmtLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayChangeAmtLabel.setText("CHANGE");

        custDisplayItemsValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        custDisplayItemsValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayItemsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayItemsValueLabel.setText(" ");

        custDisplayTotalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        custDisplayTotalValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayTotalValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayTotalValueLabel.setText(" ");

        custDisplayDiscountValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDiscountValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDiscountValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayDiscountValueLabel.setText(" ");

        custDisplayNetAmtValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        custDisplayNetAmtValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayNetAmtValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayNetAmtValueLabel.setText(" ");

        custDisplayDueAmtValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDueAmtValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDueAmtValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayDueAmtValueLabel.setText(" ");

        custDisplayChangeAmtValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayChangeAmtValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayChangeAmtValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayChangeAmtValueLabel.setText(" ");

        custDisplayItemsValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayItemsValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayItemsValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayItemsValueLabel1.setText("Rs .");

        custDisplayTotalValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayTotalValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayTotalValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayTotalValueLabel1.setText("Rs .");

        custDisplayDiscountValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDiscountValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDiscountValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayDiscountValueLabel1.setText("Rs .");

        custDisplayNetAmtValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayNetAmtValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayNetAmtValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayNetAmtValueLabel1.setText("Rs .");

        custDisplayDueAmtValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayDueAmtValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayDueAmtValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayDueAmtValueLabel1.setText("Rs .");

        custDisplayChangeAmtValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custDisplayChangeAmtValueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custDisplayChangeAmtValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        custDisplayChangeAmtValueLabel1.setText("Rs .");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custDisplayItemsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayNetAmtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayDueAmtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayChangeAmtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custDisplayDueAmtValueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayNetAmtValueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayDiscountValueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayTotalValueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(custDisplayItemsValueLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayChangeAmtValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(custDisplayNetAmtValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayDueAmtValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayItemsValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayTotalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayDiscountValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custDisplayChangeAmtValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(custDisplayItemsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custDisplayTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custDisplayDiscountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custDisplayNetAmtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custDisplayDueAmtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custDisplayChangeAmtLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custDisplayItemsValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custDisplayItemsValueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(custDisplayTotalValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custDisplayTotalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custDisplayDiscountValueLabel)
                            .addComponent(custDisplayDiscountValueLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custDisplayNetAmtValueLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(custDisplayNetAmtValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custDisplayDueAmtValueLabel)
                            .addComponent(custDisplayDueAmtValueLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custDisplayChangeAmtValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custDisplayChangeAmtValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custDisplayChangeAmtLabel;
    private javax.swing.JLabel custDisplayChangeAmtValueLabel;
    private javax.swing.JLabel custDisplayChangeAmtValueLabel1;
    private javax.swing.JLabel custDisplayDiscountLabel;
    private javax.swing.JLabel custDisplayDiscountValueLabel;
    private javax.swing.JLabel custDisplayDiscountValueLabel1;
    private javax.swing.JLabel custDisplayDueAmtLabel;
    private javax.swing.JLabel custDisplayDueAmtValueLabel;
    private javax.swing.JLabel custDisplayDueAmtValueLabel1;
    private javax.swing.JLabel custDisplayItemsLabel;
    private javax.swing.JLabel custDisplayItemsValueLabel;
    private javax.swing.JLabel custDisplayItemsValueLabel1;
    private javax.swing.JLabel custDisplayNetAmtLabel;
    private javax.swing.JLabel custDisplayNetAmtValueLabel;
    private javax.swing.JLabel custDisplayNetAmtValueLabel1;
    private javax.swing.JLabel custDisplayTotalLabel;
    private javax.swing.JLabel custDisplayTotalValueLabel;
    private javax.swing.JLabel custDisplayTotalValueLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
