package easyPOS.sale;

import appDataModels.ItemCardDataModel;
import appDataModels.ItemModel;
import control.EventManager;
import control.OnGridItemSelectListener;
import control.SalesMenuItemClickListener;
import easyPOS.NumberPanel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 *
 * @author malit
 */
public class ItemSelection extends javax.swing.JPanel {

    private OnGridItemSelectListener onGridItemSelectListener;
    /**
     * Creates new form ItemSelection
     */
    public ItemSelection() {
        initComponents();
        
        EventManager.getInstance().addSalesMenuItemClickEvent(new SalesMenuItemClickListener() {
            @Override
            public void onMenuItemClicked(SalesMenuItemClickListener.SalesMenuItem menuItem) {
                if (SalesMenuItemClickListener.SalesMenuItem.SEARCH_STOCK.equals(menuItem)) {
                    itemGridPanel.removeAll();
                    itemGridPanel.revalidate();
                    itemGridPanel.repaint();
                    
                    // load the table
                }
                else if (SalesMenuItemClickListener.SalesMenuItem.SALE_RETURN.equals(menuItem)) {
                    SaleReturnFrame saleReturnFrame = new SaleReturnFrame();
                    saleReturnFrame.setDefaultCloseOperation(SalePaymentFrame.DISPOSE_ON_CLOSE);
                    saleReturnFrame.setVisible(true);            
                }
            }
        });
    }
    
    void setOnGridItemSelectListener(OnGridItemSelectListener onGridItemSelectListener) {
        this.onGridItemSelectListener = onGridItemSelectListener;
    }
    
    
    void loadStockSearchPanel() {
        itemGridPanel.removeAll();
        itemGridPanel.setLayout(new BorderLayout()); // important

        StockSearchTablePanel sstp = new StockSearchTablePanel();
        itemGridPanel.add(sstp, BorderLayout.CENTER); // fill parent

        itemGridPanel.revalidate();
        itemGridPanel.repaint();
    }
    
    void loadNumberPad()
    {
        itemGridPanel.removeAll();
        itemGridPanel.setLayout(new BorderLayout()); // important

        NumberPanel np = new NumberPanel();
        itemGridPanel.add(np, BorderLayout.CENTER); // fill parent

        itemGridPanel.revalidate();
        itemGridPanel.repaint();
    }
    
    public void loadItemGrid(List<ItemCardDataModel> list)
    {
        itemGridPanel.removeAll();
        itemGridPanel.revalidate();
        itemGridPanel.repaint();
        
        if (list == null || list.isEmpty()) {   
            //clean
            return;
        }
        
        int COLUMNS = 3;
        
        int noOfItems = list.size();
        int rows = noOfItems / COLUMNS;
        
        if (noOfItems%COLUMNS != 0) {
            rows++;
        }
        
        //itemGridPanel.setLayout(new GridLayout(0, COLUMNS, 20, 20));
        itemGridPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));
        
        for (ItemCardDataModel item: list) {
            ItemCard card = new ItemCard();
            
            if (ItemCardDataModel.CardType.MAIN_ITEM.equals(item.getCardType())) {
                card.setData(item.getImageName(), item.getItemNameText(), ">>" );
            }
            else
            {
                card.setData(item.getImageName(), item.getItemNameText(), "Rs." + item.getItemPriceText());
            }
            
            card.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    onGridItemSelectListener.onGridItemSelect(item);
                }
            });
            itemGridPanel.add(card);
        }
        
        itemGridPanel.revalidate();
        itemGridPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemGridPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout itemGridPanelLayout = new javax.swing.GroupLayout(itemGridPanel);
        itemGridPanel.setLayout(itemGridPanelLayout);
        itemGridPanelLayout.setHorizontalGroup(
            itemGridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemGridPanelLayout.setVerticalGroup(
            itemGridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemGridPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemGridPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemGridPanel;
    // End of variables declaration//GEN-END:variables

}
