/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyPOS.sale;

import dataModels.ItemCategory;
import java.awt.GridLayout;

/**
 *
 * @author malit
 */
public class SearchStockGridPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchStockTablePanel
     */
    private static int NO_OF_COLUMNS = 8;
    public SearchStockGridPanel() {
        initComponents();
        
        initCategoryGrid();
        initItemGrid(null);
    }
    
    private void initCategoryGrid()
    {
        int noOfCategories = 10;
        
        GridLayout gridLayout =  new GridLayout(1, noOfCategories);
        jPanelSelectCategory.setLayout(gridLayout);
        
        
    }
    
    private void initItemGrid(ItemCategory category)
    {
        int noOfItems = 50;
        
        int rows = (noOfItems/NO_OF_COLUMNS);
        if (noOfItems%NO_OF_COLUMNS != 0) {
            rows += 1;
        }
        GridLayout gridLayout =  new GridLayout(rows, NO_OF_COLUMNS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSelectCategory = new javax.swing.JPanel();
        jPanelItemGrid = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelSelectCategoryLayout = new javax.swing.GroupLayout(jPanelSelectCategory);
        jPanelSelectCategory.setLayout(jPanelSelectCategoryLayout);
        jPanelSelectCategoryLayout.setHorizontalGroup(
            jPanelSelectCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSelectCategoryLayout.setVerticalGroup(
            jPanelSelectCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelItemGridLayout = new javax.swing.GroupLayout(jPanelItemGrid);
        jPanelItemGrid.setLayout(jPanelItemGridLayout);
        jPanelItemGridLayout.setHorizontalGroup(
            jPanelItemGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanelItemGridLayout.setVerticalGroup(
            jPanelItemGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelItemGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSelectCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSelectCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelItemGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelItemGrid;
    private javax.swing.JPanel jPanelSelectCategory;
    // End of variables declaration//GEN-END:variables
}
