/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyPOS.reports;

import dataModels.SaleDataModel;
import dbOperations.SalesDBOperation;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author malit
 */
public class ReportPanel extends javax.swing.JPanel {

    ArrayList<SaleDataModel> allSalesList;
    ArrayList<SaleDataModel> dailySalesList;
    ArrayList<SaleDataModel> monthlySalesList;
    ArrayList<SaleDataModel> annualSalesList;
    
    
    SalesDBOperation sdbops=new SalesDBOperation();
    
    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jTextFieldDateFrom = new javax.swing.JTextField();
        jTextFieldDateTo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBoxReportType = new javax.swing.JComboBox();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jComboBoxReportType2 = new javax.swing.JComboBox();
        jCheckBoxBarChart = new javax.swing.JCheckBox();
        jCheckBoxLineChart = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();
        jPanel31 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jTextFieldTodNwInc = new javax.swing.JTextField();
        jTextFieldTodNwCos = new javax.swing.JTextField();
        jTextFieldTodNwProf = new javax.swing.JTextField();

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextFieldDateFrom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateFromActionPerformed(evt);
            }
        });

        jTextFieldDateTo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("From:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("To:");

        jComboBoxReportType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxReportType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--All Sales--", "Sales Report Daily", "Sales Report Monthly", "Sales Report Annualy", "--All Purchase Reports--", "Purchase Report" }));
        jComboBoxReportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReportTypeActionPerformed(evt);
            }
        });

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repo.png"))); // NOI18N
        jButton26.setText("Show Report");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph.png"))); // NOI18N
        jButton27.setText("Show in Graph");
        jButton27.setToolTipText("You can see graphs using this");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButton7.setText("Print ");
        jButton7.setToolTipText("Click here,To Print this Table");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel88.setText("dd/mm/yyyy");

        jComboBoxReportType2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxReportType2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Income", "Cost", "Profit" }));
        jComboBoxReportType2.setToolTipText("Select,What kind of graph do you want?");
        jComboBoxReportType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReportType2ActionPerformed(evt);
            }
        });

        jCheckBoxBarChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxBarChart.setText("Bar Chart");
        jCheckBoxBarChart.setToolTipText("Select the chart disposition");
        jCheckBoxBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBarChartActionPerformed(evt);
            }
        });

        jCheckBoxLineChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxLineChart.setText("Line Chart");
        jCheckBoxLineChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLineChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxReportType, 0, 145, Short.MAX_VALUE)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDateFrom)
                            .addComponent(jTextFieldDateTo)
                            .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jComboBoxReportType2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxLineChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel88)
                .addGap(40, 40, 40)
                .addComponent(jComboBoxReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxReportType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxBarChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxLineChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReportMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableReport);

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Today Now"));

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel82.setText("Income:");

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel83.setText("Cost:");

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Profit:");

        jTextFieldTodNwInc.setEditable(false);
        jTextFieldTodNwInc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTodNwInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTodNwIncActionPerformed(evt);
            }
        });

        jTextFieldTodNwCos.setEditable(false);
        jTextFieldTodNwCos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTodNwCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTodNwCosActionPerformed(evt);
            }
        });

        jTextFieldTodNwProf.setEditable(false);
        jTextFieldTodNwProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTodNwProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTodNwProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTodNwInc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTodNwCos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTodNwProf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(jTextFieldTodNwInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83)
                    .addComponent(jTextFieldTodNwCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84)
                    .addComponent(jTextFieldTodNwProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFromActionPerformed

    private void jComboBoxReportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReportTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReportTypeActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        try{
            int reportType=jComboBoxReportType.getSelectedIndex();

            if(jTextFieldDateFrom.getText().equals("")&&jTextFieldDateTo.getText().equals("")){
                switch(reportType){
                    case 0:allSalesLoadTable("","");break;//all
                    case 1:dailySalesLoadTable(0,"","");break;//daily
                    case 2:monthlySalesLoadTable(1,"","");break;//monthly
                    case 3:annualSalesLoadTable(2,"","");break;//annual
                    case 4:suppliesLoadTableForReport(0,"","","");break;//
                    case 5:suppliesLoadTableForReport(0,"","","");break;//
                    default:JOptionPane.showMessageDialog(this, "Error occur...!");break;
                }
            }else{
                String dateFrom="";
                String dateTo="";
                if(jTextFieldDateFrom.getText().equals("")){
                }else{
                    dateFrom=util.DateTimeUtil.dateFormatForDB(jTextFieldDateFrom.getText());
                }
                if(jTextFieldDateTo.getText().equals("")){
                }else{
                    dateTo=util.DateTimeUtil.dateFormatForDB(jTextFieldDateTo.getText());
                }
                switch(reportType){
                    case 0:allSalesLoadTable(dateFrom,dateTo);break;//all
                    case 1:dailySalesLoadTable(3,dateFrom,dateTo);break;//daily
                    case 2:monthlySalesLoadTable(4,dateFrom,dateTo);break;//monthly
                    case 3:annualSalesLoadTable(5,dateFrom,dateTo);break;//annual
                    case 4:suppliesLoadTableForReport(0,"","","");break;//
                    case 5:suppliesLoadTableForReport(1,dateFrom,dateTo,"");break;//
                    default:JOptionPane.showMessageDialog(this, "Error occur...!");break;
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Incorrect input method for 'Date' !");
        }

    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        int input1=jComboBoxReportType.getSelectedIndex();
        int input2=jComboBoxReportType2.getSelectedIndex();
        String dateFrom="";
        String dateTo="";
        if(jTextFieldDateFrom.getText().equals("")){
        }else{
            dateFrom=util.DateTimeUtil.dateFormatForDB(jTextFieldDateFrom.getText());
        }
        if(jTextFieldDateTo.getText().equals("")){
        }else{
            dateTo=util.DateTimeUtil.dateFormatForDB(jTextFieldDateTo.getText());
        }
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        try{
            switch(input2){
                //income************************************************************
                case 0:
                if(input1==1){//daily
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        dailySalesList=sdbops.getTotalSales(0,"","");
                    }else{
                        dailySalesList=sdbops.getTotalSales(3,dateFrom,dateTo);
                    }
                    for(int i=0;i<=dailySalesList.size()-1;i++){
                        dataset.setValue(dailySalesList.get(i).getIncome(), "Income",dailySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Daily Income", "Date", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Daily Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Daily Income", "Date", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Daily Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==2){//monthly
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        monthlySalesList=sdbops.getTotalSales(1,"","");
                    }else{
                        monthlySalesList=sdbops.getTotalSales(4,dateFrom,dateTo);
                    }
                    for(int i=0;i<=monthlySalesList.size()-1;i++){
                        dataset.setValue(monthlySalesList.get(i).getIncome(), "Income",monthlySalesList.get(i).getMonthName()+monthlySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Monthly Income", "Month(Date)", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Monthly Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Monthly Income", "Month(Date)", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Monthly Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==3){//annualy
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        annualSalesList=sdbops.getTotalSales(2,"","");
                    }else{
                        annualSalesList=sdbops.getTotalSales(5,dateFrom,dateTo);
                    }
                    for(int i=0;i<=annualSalesList.size()-1;i++){
                        dataset.setValue(annualSalesList.get(i).getIncome(), "Income",annualSalesList.get(i).getYearName());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Annual Income", "Year", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Annual Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Annual Income", "Year", "Income(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Annual Income", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                }
                break;

                //cost**************************************************************
                case 1:
                if(input1==1){//daily
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        dailySalesList=sdbops.getTotalSales(0,"","");
                    }else{
                        dailySalesList=sdbops.getTotalSales(3,dateFrom,dateTo);
                    }
                    for(int i=0;i<=dailySalesList.size()-1;i++){
                        dataset.setValue(dailySalesList.get(i).getCost(), "Cost",dailySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Daily Costs of Sales", "Date", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Daily Costs of Sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Daily Costs of Sales", "Date", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Daily Costs of Sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==2){//monthly
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        monthlySalesList=sdbops.getTotalSales(1,"","");
                    }else{
                        monthlySalesList=sdbops.getTotalSales(4,dateFrom,dateTo);
                    }
                    for(int i=0;i<=monthlySalesList.size()-1;i++){
                        dataset.setValue(monthlySalesList.get(i).getCost(), "Cost",monthlySalesList.get(i).getMonthName()+monthlySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Monthly Costs of sales", "Month(Date)", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Monthly Costs of Sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Monthly Costs of sales", "Month(Date)", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Monthly Costs of Sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==3){//annualy
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        annualSalesList=sdbops.getTotalSales(2,"","");
                    }else{
                        annualSalesList=sdbops.getTotalSales(5,dateFrom,dateTo);
                    }
                    for(int i=0;i<=annualSalesList.size()-1;i++){
                        dataset.setValue(annualSalesList.get(i).getCost(), "Cost",annualSalesList.get(i).getYearName());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Annual Costs of sales", "Year", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Annual Cost of sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Annual Costs of sales", "Year", "Cost(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Annual Cost of sales", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                }
                break;

                //profit************************************************************
                case 2:
                if(input1==1){//daily
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        dailySalesList=sdbops.getTotalSales(0,"","");
                    }else{
                        dailySalesList=sdbops.getTotalSales(3,dateFrom,dateTo);
                    }
                    for(int i=0;i<=dailySalesList.size()-1;i++){
                        dataset.setValue(dailySalesList.get(i).getProfit(), "Profit",dailySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Daily Profits", "Date", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Daily Profits", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Daily Profits", "Date", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Daily Profits", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==2){//monthly
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        monthlySalesList=sdbops.getTotalSales(1,"","");
                    }else{
                        monthlySalesList=sdbops.getTotalSales(4,dateFrom,dateTo);
                    }
                    for(int i=0;i<=monthlySalesList.size()-1;i++){
                        dataset.setValue(monthlySalesList.get(i).getProfit(), "Profit",monthlySalesList.get(i).getMonthName()+monthlySalesList.get(i).getDate());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Monthly Profit", "Date", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Monthly Profits", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Monthly Profit", "Date", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Monthly Profits", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }

                }else if(input1==3){//annualy
                    if(jTextFieldDateFrom.getText().equals("") && jTextFieldDateTo.getText().equals("")){
                        annualSalesList=sdbops.getTotalSales(2,"","");
                    }else{
                        annualSalesList=sdbops.getTotalSales(5,dateFrom,dateTo);
                    }
                    for(int i=0;i<=annualSalesList.size()-1;i++){
                        dataset.setValue(annualSalesList.get(i).getProfit(), "Profit",annualSalesList.get(i).getYearName());
                    }
                    if(jCheckBoxBarChart.isSelected()){
                        JFreeChart chart=ChartFactory.createBarChart("Annual Profit", "Year", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Bar Chart For Annual Profit", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                    if(jCheckBoxLineChart.isSelected()){
                        JFreeChart chart=ChartFactory.createLineChart("Annual Profit", "Year", "Profit(Rs)", dataset, PlotOrientation.VERTICAL, false, true, false);
                        CategoryPlot p=chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.BLUE);
                        ChartFrame frame=new ChartFrame("Line Chart For Annual Profit", chart);
                        frame.setVisible(true);
                        frame.setSize(800, 500);
                    }
                }
                break;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "System can not show graphs for reports!");
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            boolean result=jTableReport.print();
            if(result){
            }else{
                JOptionPane.showMessageDialog(this, "Printer has stopped working !");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error occur..\nCan not do your printing process !");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBoxReportType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReportType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReportType2ActionPerformed

    private void jCheckBoxBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBarChartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxBarChartActionPerformed

    private void jCheckBoxLineChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLineChartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxLineChartActionPerformed

    private void jTableReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReportMouseClicked
        //        try{
            //            String dt=jTableReport.getValueAt(jTableReport.getSelectedRow(),2).toString();
            //            String res=sdbops.getSalesItems((int) jTableReport.getValueAt(jTableReport.getSelectedRow(),1),dateFormatForDB(dt));
            //            if(res.equals("")){
                //                JOptionPane.showMessageDialog(this, "Olden data has been cleared!");
                //            }else{
                //                Notes n=new Notes();
                //                n.setVisible(true);
                //                n.setPrintPreview(res);
                //                n.setDefaultCloseOperation(WIDTH);
                //            }
            //        }catch(Exception e){
            //            JOptionPane.showMessageDialog(this, "Select the row !");
            //        }
    }//GEN-LAST:event_jTableReportMouseClicked

    private void jTextFieldTodNwIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTodNwIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTodNwIncActionPerformed

    private void jTextFieldTodNwCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTodNwCosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTodNwCosActionPerformed

    private void jTextFieldTodNwProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTodNwProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTodNwProfActionPerformed


    void allSalesLoadTable(String searchInput1,String searchInput2){
//        allSalesList=sdbops.getAllSales(searchInput1, searchInput2);
//        if(allSalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            AllSalesLoadTbl aslt=new AllSalesLoadTbl(allSalesList);
//            jTableReport.setModel(aslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                jTableReport.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
//                for(int i=4;i<10;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }   
//        }
    }
    void dailySalesLoadTable(int situation,String searchInput1,String searchInput2){
//        dailySalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(dailySalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            DailySalesLoadTbl dslt=new DailySalesLoadTbl(dailySalesList);
//            jTableReport.setModel(dslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=2;i<5;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }        
    }
    void monthlySalesLoadTable(int situation,String searchInput1,String searchInput2){
//        monthlySalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(monthlySalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            MonthlySalesLoadTbl mslt=new MonthlySalesLoadTbl(monthlySalesList);
//            jTableReport.setModel(mslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=3;i<6;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }
    }
    void annualSalesLoadTable(int situation,String searchInput1,String searchInput2){
//        annualSalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(annualSalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            AnnualSalesLoadTbl anuslt=new AnnualSalesLoadTbl(annualSalesList);
//            jTableReport.setModel(anuslt); 
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=3;i<6;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }
    } 
    
    void suppliesLoadTableForReport(int situation,String searchInput1,String searchInput2,String searchInput3){
//        suppliesList=supp.getSuppliesData(situation,searchInput1,searchInput2,searchInput3);
//        if(suppliesList==null){
//            JOptionPane.showMessageDialog(rootPane, "No any data according to your input !");
//        }else{
//            SuppliesLoadTbl sltbl=new SuppliesLoadTbl(suppliesList);
//            jTableReport.setModel(sltbl); 
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=4;i<9;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }        
//        }
    }
    void suppliesLoadTableForSuppliers(int situation,String searchInput1,String searchInput2,String searchInput3){
//        suppliesList=supp.getSuppliesData(situation,searchInput1,searchInput2,searchInput3);
//        if(suppliesList==null){
//            JOptionPane.showMessageDialog(rootPane, "No any data according to your input !");
//        }else{
//            SuppliesLoadTbl sltbl=new SuppliesLoadTbl(suppliesList);
//            jTableSupplies.setModel(sltbl);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=1;i<9;i++){
//                    jTableSupplies.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }            
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBoxBarChart;
    private javax.swing.JCheckBox jCheckBoxLineChart;
    private javax.swing.JComboBox jComboBoxReportType;
    private javax.swing.JComboBox jComboBoxReportType2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableReport;
    private javax.swing.JTextField jTextFieldDateFrom;
    private javax.swing.JTextField jTextFieldDateTo;
    private javax.swing.JTextField jTextFieldTodNwCos;
    private javax.swing.JTextField jTextFieldTodNwInc;
    private javax.swing.JTextField jTextFieldTodNwProf;
    // End of variables declaration//GEN-END:variables
}
