package easyPOS.reports;

import appDataModels.APIHeaderData;
import appDataModels.InstituteModel;
import control.ApplicationDataManager;
import control.EasyPosLogger;
import control.RuntimeDataManager;
import control.ZebraShippingLabelPrinter;
import dataModels.Language;
import dataModels.SaleDataModel;
import dbOperations.SalesDBOperation;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRootPane;
import javax.swing.SwingWorker;
import easyPOS.localization.ApplicationMessages;
import serverDataModels.OnlineOrder;
import serverResponseDataModel.CommonResponse;
import tableModels.OnlineOrdersTbl;
import uiUtil.EasyPOSMessageDialog;
import uiUtil.LoadingGlassPane;
import webService.ServerAPIConnection;

/**
 *
 * @author malit
 */
public class ReportPanel extends javax.swing.JPanel implements control.LanguageChangeListener {

    ArrayList<SaleDataModel> allSalesList;
    ArrayList<SaleDataModel> dailySalesList;
    ArrayList<SaleDataModel> monthlySalesList;
    ArrayList<SaleDataModel> annualSalesList;

    SalesDBOperation sdbops = new SalesDBOperation();

    private List<OnlineOrder> currentOrders = new ArrayList<>();
    
    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
        switchLanguage();
        control.EventManager.getInstance().addLanguageChangeListener(this);
    }

    @Override
    public void onLanguageChanged() {
        switchLanguage();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBoxOrderStatus = new javax.swing.JComboBox();
        jButtonShowOrders = new javax.swing.JButton();
        jButtonPrintShippingLabel = new javax.swing.JButton();
        jDateChooserOrdersFrom = new com.toedter.calendar.JDateChooser();
        jDateChooserOrdersTo = new com.toedter.calendar.JDateChooser();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("From:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("To:");

        jComboBoxOrderStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--All Sales--", "Sales Report Daily", "Sales Report Monthly", "Sales Report Annualy", "--All Purchase Reports--", "Purchase Report" }));
        jComboBoxOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrderStatusActionPerformed(evt);
            }
        });

        jButtonShowOrders.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonShowOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repo.png"))); // NOI18N
        jButtonShowOrders.setText("Show Report");
        jButtonShowOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowOrdersActionPerformed(evt);
            }
        });

        jButtonPrintShippingLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPrintShippingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButtonPrintShippingLabel.setText("Print ");
        jButtonPrintShippingLabel.setToolTipText("Click here,To Print this Table");
        jButtonPrintShippingLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintShippingLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPrintShippingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonShowOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserOrdersFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jDateChooserOrdersTo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooserOrdersFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jDateChooserOrdersTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrintShippingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReportMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrderStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrderStatusActionPerformed

    private void jButtonShowOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowOrdersActionPerformed
        java.util.Date fromDate = jDateChooserOrdersFrom.getDate();
        java.util.Date toDate = jDateChooserOrdersTo.getDate();

        String dateFrom = fromDate != null ? util.DateTimeUtil.getDBFormatStringFromDate(fromDate) : "";
        String dateTo = toDate != null ? util.DateTimeUtil.getDBFormatStringFromDate(toDate) : "";

        String selectedStatus = "";
        int statusIdx = jComboBoxOrderStatus.getSelectedIndex();
        if (statusIdx > 0) {
            selectedStatus = jComboBoxOrderStatus.getSelectedItem().toString();
        }

        loadOnlineOrders(dateFrom, dateTo, selectedStatus);
    }//GEN-LAST:event_jButtonShowOrdersActionPerformed

    private void jButtonPrintShippingLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintShippingLabelActionPerformed
        if (!(jTableReport.getModel() instanceof OnlineOrdersTbl)) {
            EasyPOSMessageDialog.showLocalizedError(this, ApplicationMessages.ERROR_GENERIC);
            return;
        }
        OnlineOrdersTbl model = (OnlineOrdersTbl) jTableReport.getModel();
        List<OnlineOrder> selected = model.getSelectedOrders();
        if (selected.isEmpty()) {
            EasyPOSMessageDialog.showLocalizedWarning(this, ApplicationMessages.VALIDATION_SELECT_ITEM);
            return;
        }
        InstituteModel institute = RuntimeDataManager.getInstance().getRuntimeData().getSelectedInstitute();
        if (institute == null) {
            EasyPOSMessageDialog.showLocalizedError(this, ApplicationMessages.ERROR_GENERIC);
            return;
        }
        new ZebraShippingLabelPrinter().print(selected, institute);
    }//GEN-LAST:event_jButtonPrintShippingLabelActionPerformed

    private void jTableReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReportMouseClicked
        //        try{
            //            String dt=jTableReport.getValueAt(jTableReport.getSelectedRow(),2).toString();
            //            String res=sdbops.getSalesItems((int) jTableReport.getValueAt(jTableReport.getSelectedRow(),1),dateFormatForDB(dt));
            //            if(res.equals("")){
                //                JOptionPane.showMessageDialog(this, "Olden data has been cleared!");
                //            }else{
                //                Notes n=new Notes();
                //                n.setVisible(true);
                //                n.setPrintPreview(res);
                //                n.setDefaultCloseOperation(WIDTH);
                //            }
            //        }catch(Exception e){
            //            JOptionPane.showMessageDialog(this, "Select the row !");
            //        }
    }//GEN-LAST:event_jTableReportMouseClicked


    public void loadData() {
        loadOnlineOrders("", "", "");
    }

    private void loadOnlineOrders(String dateFrom, String dateTo, String status) {
        JRootPane root = getRootPane();
        LoadingGlassPane loader = new LoadingGlassPane();
        root.setGlassPane(loader);

        SwingWorker<CommonResponse, Void> worker = new SwingWorker<CommonResponse, Void>() {
            @Override
            protected CommonResponse doInBackground() {
                loader.start();
                APIHeaderData headerData = new APIHeaderData();
                headerData.setInstituteId(RuntimeDataManager.getInstance().getRuntimeData().getInstituteId());
                headerData.setTerminalId(RuntimeDataManager.getInstance().getRuntimeData().getTerminalId());
                return ServerAPIConnection.getInstance(headerData).getOnlineOrders(dateFrom, dateTo, status);
            }

            @Override
            protected void done() {
                loader.stop();
                try {
                    CommonResponse response = get();
                    if (response.getAPIResponse().isSuccess()) {
                        currentOrders = (List<OnlineOrder>) response.getData();

                        // Populate status combo with unique values from this response
                        Set<String> statuses = new LinkedHashSet<>();
                        for (OnlineOrder o : currentOrders) {
                            if (o.order_status != null && !o.order_status.isEmpty()) {
                                statuses.add(o.order_status);
                            }
                        }
                        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
                        comboModel.addElement("-- All --");
                        for (String s : statuses) {
                            comboModel.addElement(s);
                        }
                        jComboBoxOrderStatus.setModel(comboModel);

                        jTableReport.setModel(new OnlineOrdersTbl(currentOrders));
                        jTableReport.getColumnModel().getColumn(0).setMaxWidth(55);
                    } else {
                        EasyPOSMessageDialog.showErrorMessageDialog(ReportPanel.this.getRootPane(), response.getAPIResponse());
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    EasyPOSMessageDialog.showUnexpectedError(ReportPanel.this.getRootPane(), ex.getMessage());
                    EasyPosLogger.getInstance().log(EasyPosLogger.LogLevel.ERROR, ex.toString());
                }
            }
        };

        loader.start();
        worker.execute();
    }

    void allSalesLoadTable(String searchInput1,String searchInput2){
//        allSalesList=sdbops.getAllSales(searchInput1, searchInput2);
//        if(allSalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            AllSalesLoadTbl aslt=new AllSalesLoadTbl(allSalesList);
//            jTableReport.setModel(aslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                jTableReport.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
//                for(int i=4;i<10;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }   
//        }
    }
    void dailySalesLoadTable(int situation,String searchInput1,String searchInput2){
//        dailySalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(dailySalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            DailySalesLoadTbl dslt=new DailySalesLoadTbl(dailySalesList);
//            jTableReport.setModel(dslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=2;i<5;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }        
    }
    void monthlySalesLoadTable(int situation,String searchInput1,String searchInput2){
//        monthlySalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(monthlySalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            MonthlySalesLoadTbl mslt=new MonthlySalesLoadTbl(monthlySalesList);
//            jTableReport.setModel(mslt);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=3;i<6;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }
    }
    void annualSalesLoadTable(int situation,String searchInput1,String searchInput2){
//        annualSalesList=sdbops.getTotalSales(situation,searchInput1,searchInput2);
//        if(annualSalesList==null){
//            JOptionPane.showMessageDialog(this, "No any data according to your input !");
//        }else{
//            AnnualSalesLoadTbl anuslt=new AnnualSalesLoadTbl(annualSalesList);
//            jTableReport.setModel(anuslt); 
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=3;i<6;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }
//        }
    } 
    
    void suppliesLoadTableForReport(int situation,String searchInput1,String searchInput2,String searchInput3){
//        suppliesList=supp.getSuppliesData(situation,searchInput1,searchInput2,searchInput3);
//        if(suppliesList==null){
//            JOptionPane.showMessageDialog(rootPane, "No any data according to your input !");
//        }else{
//            SuppliesLoadTbl sltbl=new SuppliesLoadTbl(suppliesList);
//            jTableReport.setModel(sltbl); 
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=4;i<9;i++){
//                    jTableReport.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }        
//        }
    }
    void suppliesLoadTableForSuppliers(int situation,String searchInput1,String searchInput2,String searchInput3){
//        suppliesList=supp.getSuppliesData(situation,searchInput1,searchInput2,searchInput3);
//        if(suppliesList==null){
//            JOptionPane.showMessageDialog(rootPane, "No any data according to your input !");
//        }else{
//            SuppliesLoadTbl sltbl=new SuppliesLoadTbl(suppliesList);
//            jTableSupplies.setModel(sltbl);
//                DefaultTableCellRenderer rightRenderer=new DefaultTableCellRenderer();
//                rightRenderer.setHorizontalAlignment(jLabel1.RIGHT);
//                for(int i=1;i<9;i++){
//                    jTableSupplies.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
//                }            
//        }
    }
    private void switchLanguage() {
        Language appLang = ApplicationDataManager.getInstance().getApplicationLanguage();
        Locale locale = (appLang == Language.SINHALA) ? new Locale("si", "LK") : Locale.ENGLISH;
        ResourceBundle resourceBundle = ResourceBundle.getBundle("easyPOS/reports/Bundle", locale);
        if (appLang == Language.SINHALA) {
            try {
                Font customFont = Font.createFont(Font.TRUETYPE_FONT,
                        ApplicationDataManager.getInstance().getSinhalaFontFile()).deriveFont(14f);
                GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                ge.registerFont(customFont);
                jLabel4.setFont(customFont);
                jLabel32.setFont(customFont);
                jButtonShowOrders.setFont(customFont);
                jButtonPrintShippingLabel.setFont(customFont);
            } catch (IOException | FontFormatException e) {
                System.err.println(e);
            }
        }
        jLabel4.setText(resourceBundle.getString("ReportPanel.jLabel4.text"));
        jLabel32.setText(resourceBundle.getString("ReportPanel.jLabel32.text"));
        jButtonShowOrders.setText(resourceBundle.getString("ReportPanel.jButton26.text"));
        jButtonPrintShippingLabel.setText(resourceBundle.getString("ReportPanel.jButton7.text"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrintShippingLabel;
    private javax.swing.JButton jButtonShowOrders;
    private javax.swing.JComboBox jComboBoxOrderStatus;
    private com.toedter.calendar.JDateChooser jDateChooserOrdersFrom;
    private com.toedter.calendar.JDateChooser jDateChooserOrdersTo;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableReport;
    // End of variables declaration//GEN-END:variables
}
